name: "trivy-plugin"
repository: github.com/LucianErick/trivy-plugin
version: "0.0.0"
usage: trivy plugin
description: |-
  A Trivy plugin.
platforms:
  -
    uri: https://github.com/LucianErick/trivy-plugin/releases/download/v0.0.0/trivy-plugin_0.0.0_Linux-amd64.tar.gz
    bin: ./trivy-plugin
    